name: Open Microservices Validation

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  oms-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Open Microservices CLI
        run: yarn add @microservices/oms

      - name: Validate `oms.yml`
        run: node_modules/.bin/oms validate
